services:
  app:
    build: .
    container_name: mobility_app
    volumes:
      - .:/app
      - ./data:/app/data
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      
    command: python /app/src/agent/graph.py