services:
  app:
    build: .
    container_name: mobility_app
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - WATCHFILES_FORCE_POLLING=true
    network_mode: "host" # Permet d'accéder à Ollama sur l'hôte facilement
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true 
    tty: true
    command: python src/agent/test_question_sql.py